config/routes.rb
Rails.application.routes.draw do

  resources :commits
  root 'dashboard#root'
  get '/projects/dashboard' => 'projects#dashboard'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get '/projects/:id/get_recent_activity' => 'projects#get_recent_activity'
  get '/projects/:id/get_language_statistics' => 'projects#get_language_statistics'

  resources :projects do
    resources :milestones
    resources :issues
    resources :commits
  end
  resources :users

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/analytics' => 'analytics#index'
  get '/analytics/1' => 'analytics#projects_vs_collaborators'#, :defaults => { :format => 'json' }
  get '/analytics/2' => 'analytics#number_of_commits_for_active_projects'

  post '/event_handler' => 'dashboard#event_handler'
  get '/notifications' => 'dashboard#notifications'

end

app/models/milestone.rb
# == Schema Information
#
# Table name: milestones
#
#  id              :integer          not null, primary key
#  title           :string
#  description     :string
#  state           :string
#  project_id      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  collaborator_id :integer
#  date            :datetime
#

class Milestone < ActiveRecord::Base
  belongs_to :project
  belongs_to :collaborator

  # validation
  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  validates :description, length: { maximum: 500 }

  def oldest_milestone(project)
  	project.milestones.order(created_at: :asc).first
  end

  def most_recent_milestone(project)
  	project.milestones.order(created_at: :desc).first
  end

  def newest_milestone_created_by_collaborator(collaborator)
  	collaborator.milestones.order(created_at: :desc).first
  end

  def self.newest_milestone_on_site
  	self.all.order(created_at: :desc).first
  end

  def self.sorted_by_date_desc
    self.order('date desc')
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]
  before_filter :require_login

  def index
    @project = Project.find(params[:project_id])
    @milestones = @project.milestones
    # @milestones = Milestone.all
  end

  def show
    @milestone = Milestone.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  def new
    @milestone = Milestone.new
    @project = Project.find(params[:project_id])
  end

  def edit
    @milestone = Milestone.find(params[:id])
    @project = Project.find(params[:project_id])
  end


  def create
    @milestone = Milestone.new(milestone_params)
    @project = Project.find(params[:project_id])
    @milestone.project = @project
    @milestone.collaborator = current_user.collaborator

    respond_to do |format|
      if @milestone.save

        #Create New Milestone on Github API (Post Request)
        github = Github.new user: current_user.username, repo:"#{@project.name}"
        github.oauth_token = session["user_token"]

        github.issues.milestones.create title: "#{@milestone.title}",
          # state: "#{@milestone.state}",
          description: "#{@milestone.description}"
            #   due_on: "Time"

        format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: project_milestone_path }
      else
        format.html { render :new }
        format.json { render json: project_milestone_path.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to project_milestone_path, notice: 'Milestone was successfully updated.' }
        format.json { render :show, status: :ok, location: project_milestone_path }
      else
        format.html { render :edit }
        format.json { render json: project_milestone_path.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to milestones_url, notice: 'Milestone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_milestone
      @milestone = Milestone.find(params[:id])
    end

    def milestone_params
      params.require(:milestone).permit(:title, :description, :state)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_for([@project, @milestone ]) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<h1>Editing Milestone</h1>

<%= render 'form' %>

<%= link_to 'Show', project_milestone_path(@project, @milestone), class: "btn btn-primary btn-sm" %>
<%= link_to 'Back', project_milestones_path, class: "btn btn-primary btn-sm" %>

app/views/milestones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Milestones</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>State</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @milestones.each do |milestone| %>
      <tr>
        <td><%= milestone.title %></td>
        <td><%= milestone.description %></td>
        <td><%= milestone.state %></td>
        <td><%= milestone.project_id %></td>
        <td><%= link_to 'Show', project_milestone_path(@project, milestone) %></td>
        <td><%= link_to 'Edit', edit_project_milestone_path(@project, milestone) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Milestone', new_project_milestone_path %>

app/views/milestones/new.html.erb
<h1>New Milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', project_milestones_path %>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @milestone.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @milestone.description %>
</p>

<p>
  <strong>State:</strong>
  <%= @milestone.state %>
</p>

<p>
  <strong>Project:</strong>
  <%= @milestone.project_id %>
</p>

<%= link_to 'Edit', edit_project_milestone_path(@project, @milestone) %> |
<%= link_to 'Back', project_path(@project) %>