config/routes.rb
Rails.application.routes.draw do

  resources :commits
  root 'dashboard#root'
  get '/projects/dashboard' => 'projects#dashboard'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get '/projects/:id/get_recent_activity' => 'projects#get_recent_activity'
  get '/projects/:id/get_language_statistics' => 'projects#get_language_statistics'

  resources :projects do
    resources :milestones
    resources :issues
    resources :commits
  end
  resources :users

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/analytics' => 'analytics#index'
  get '/analytics/1' => 'analytics#projects_vs_collaborators'#, :defaults => { :format => 'json' }
  get '/analytics/2' => 'analytics#number_of_commits_for_active_projects'

  post '/event_handler' => 'dashboard#event_handler'
  get '/notifications' => 'dashboard#notifications'

end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id              :integer          not null, primary key
#  title           :string
#  body            :text
#  state           :string
#  created_at      :datetime         not null
#  closed_at       :string
#  updated_at      :datetime         not null
#  project_id      :integer
#  collaborator_id :integer
#

class Issue < ActiveRecord::Base
  belongs_to :project
  belongs_to :collaborator
  #validation
  validates :title, presence: true
  validates :title, length: { minimum: 3 }
  validates :body, length: { maximum: 500 }


  def milestones
    return 'no project' unless project
    project.milestones
  end

  def self.sorted_by_date_desc
    self.order('date desc')
  end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_filter :require_login, :except => :event_handler
  protect_from_forgery except: :event_handler

  def index
    @project = Project.find(params[:project_id])
    @issues = @project.issues
  end

  def show
    @project = Project.find(params[:project_id])
  end

  def new
    @issue = Issue.new
    @project = Project.find(params[:project_id])
  end

  def edit
    @project = Project.find(params[:project_id])
    @issue = Issue.find(params[:id])
  end

  def create
      @project = Project.find(params[:project_id])
      @issue = Issue.new(issue_params)
      @issue.project = @project

    respond_to do |format|
      if @issue.save

            # Github object to create new issue
             github = Github.new user: current_user.username, repo:"#{@project.name}"
             github.oauth_token = session["user_token"]

             #Gathering milestone ID from new issues form
             milestone_id = params['issue']['milestones']
      begin
             #Creating new issue on github with milestone ID
             github.issues.create title: "#{@issue.title}",
               body: "#{@issue.body}"
               # assignee: "octocat",
               # milestone: "#{milestone_id}"
     rescue Github::Error::ServiceError
       format.html { redirect_to project_issue_path(@project, @issue), notice: 'Issue has been saved on local but you do not have access to push to remote.' }
     end

        format.html { redirect_to project_issue_path(@project, @issue), notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: project_issue_path }
      else
        format.html { render :new }
        format.json { render json: project_issue_path.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    binding.pry
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to project_issue_path, notice: 'Milestone was successfully updated.'  }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_issue
      @issue = Issue.find(params[:id])
    end

    def issue_params
      params.require(:issue).permit(:title, :body, :milestone_id, :created_at, :closed_at)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_for([@project, @issue]) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>
      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :milestone %><br>
    <%= f.collection_select(:milestones, @project.milestones, :id, :title ) %>
  </div>

  <div class="actions" >
      <%= f.submit%>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Edit An Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', project_issue_path(@project, @issue), class: "btn btn-primary btn-sm" %>
<%= link_to 'Back', project_issues_path, class: "btn btn-primary btn-sm" %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Milestone</th>
      <th>Created at</th>
      <th>Closed at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.body %></td>
        <td><%= issue.created_at %></td>
        <td><%= issue.closed_at %></td>
        <td><%= link_to 'Show', project_issue_path(@project, issue) %></td>
        <td><%= link_to 'Edit', edit_project_issue_path(@project, issue) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/issues/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', project_issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @issue.body %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @issue.project_id %>
</p>


<%= link_to 'Edit', edit_project_issue_path(@project, @issue), class: "btn btn-primary btn-sm" %>
<%= link_to 'Back', project_path(@project), class: "btn btn-primary btn-sm" %>
</div>