config/routes.rb
Rails.application.routes.draw do

  resources :commits
  root 'dashboard#root'
  get '/projects/dashboard' => 'projects#dashboard'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get '/projects/:id/get_recent_activity' => 'projects#get_recent_activity'
  get '/projects/:id/get_language_statistics' => 'projects#get_language_statistics'

  resources :projects do
    resources :milestones
    resources :issues
    resources :commits
  end
  resources :users

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/analytics' => 'analytics#index'
  get '/analytics/1' => 'analytics#projects_vs_collaborators'#, :defaults => { :format => 'json' }
  get '/analytics/2' => 'analytics#number_of_commits_for_active_projects'

  post '/event_handler' => 'dashboard#event_handler'
  get '/notifications' => 'dashboard#notifications'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id             :integer          not null, primary key
#  name           :string
#  github_repo_id :integer
#  admin_id       :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  url            :string
#  description    :text
#  active         :boolean          default(TRUE)
#

class Project < ActiveRecord::Base

	has_many :collaborators_projects
	has_many :collaborators, -> { uniq }, through: :collaborators_projects
	# the above uses a scope block http://stackoverflow.com/questions/16569994/deprecation-warning-when-using-has-many-through-uniq-in-rails-4
	has_many :milestones
	has_many :issues
	has_many :commits
	belongs_to :admin
	# Can we specify to allow nil nto be set to true
	delegate :user, to: :admin, allow_nil: true

	def self.with_the_most_collaborators
		self.sort_by_number_of_collaborators.first
	end

	def self.sort_by_number_of_collaborators
		self.group('projects.id')
				.select('projects.*,count(collaborators.id) as collaborators_count')
				.joins(:collaborators)
				.order('collaborators_count desc')
	end

	def self.active
    self.where(active: true)
  end

  def self.inactive
    self.where(active: false)
  end

  def add_collaborator(collaborator)
    self.collaborators.push(collaborator)
  end

	def self.sort_by_number_of_issues
		self.select('projects.*, count(issues.id) as issues_count')
			.joins(:issues)
			.group('projects.id')
			.order('issues_count desc')
	end

	def self.name_and_number_of_collaborators
		self.group('projects.name').select('project.name').joins(:collaborators).count('collaborators.id')
	end

	def self.sort_projects_and_number_of_collaborators_desc
		self.name_and_number_of_collaborators.sort{|a,b| b[1] <=> a[1]}
	end

	def get_milestones
		client = Adapters::MilestonesClient.new
		results = client.get_milestones_for_project(self.user.username,self)
	end

	def get_issues
		client = Adapters::IssuesClient.new
		results = client.get_issues_for_project(self.user.username,self)
	end

	def get_commits
		client = Adapters::CommitsClient.new
		results = client.get_commits_for_project(self.user.username,self)
	end

	def get_activity_feed
		client = Adapters::ActivityFeedClient.new
		results = client.get_activity_feed_for_project(self.user.username,self)
	end

	def get_language_statistics
		client = Adapters::LanguageStatisticsClient.new
		results = client.get_language_statistics_for_project(self.user.username,self)
	end

	def self.find_language_statistics(all_repo_events)
		all_repo_events
	end

  def self.find_push_events(all_repo_events)
		push_events = []
		all_repo_events.each do |event|
			if event["type"] == "PushEvent"
				push_events << event
			end
		end
		return push_events
	end

	def commits_sorted_desc
		self.commits.sorted_by_date_desc
	end

	def five_most_recent_commits
		commits_sorted_desc.first(5)
	end

	def issues_sorted_desc
		self.issues.sorted_by_date_desc
	end

	def five_most_recent_issues
		issues_sorted_desc.first(5)
	end

	def milestones_sorted_desc
		self.milestones.sorted_by_date_desc
	end

	def five_most_recent_milestones
		milestones_sorted_desc.first(5)
	end

	def self.sort_by_number_of_commits
		self.select('projects.*, count(commits.id) as count_commits').group('projects.id').joins(:commits).order('count_commits desc')
	end

	def self.number_of_commits_by_user_on_active_projects(user)
		self.active.map do |project|
			project.commits.where('collaborator_id = ?', user.collaborator.id).count
		end
		# Project.group('projects.name').joins(:commits).joins(:collaborators).count('commits.collaborator_id = 1')
		end

end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController

	def index
		@projects = Project.all
		render json: @projects
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :get_recent_activity, :get_language_statistics]
  before_filter :require_login

  def index
    @projects = Project.all
  end

  def dashboard
    @projects = current_user.collaborator.projects.active
    render :json => @projects
  end


  def show
    respond_to do |format|
      format.html { render :show }
      format.json {
        html_string = render_to_string 'show.html.erb', layout: false
        render json: {template: html_string}
      }
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
    if current_user.admin.id != @project.admin_id
      flash[:notice] = "You must be this project's administrator in order to edit this project."
      redirect_to project_path(params[:id])
    end
  end

  def create
    @project = Project.new(project_params)
    @project.admin = current_user.admin
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if !params[:mark_inactive] #normal mode
      new_collaborator = Collaborator.find_by(user_id: User.find(params[:project][:user]))
      @project.add_collaborator(new_collaborator)
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, notice: "You've successfully updated your project." }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else #handle specific ajax call from dashboard to mark inactive
      @project.active = false
      @project.save
      render json: @project.id
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_recent_activity
    recent_events = @project.get_activity_feed
    html = render_to_string '/_activity_feed', :locals => {events: recent_events}, layout: false

    render json: {html: html}
  end

  def get_language_statistics
    language_statistics = @project.get_language_statistics
    html = render_to_string '/_language_statistics', :locals => {languages: language_statistics}, layout: false
    render json: {html: html}
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :github_id, :admin_id, :active, :new_collab)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="row">
<div class="col-lg-6">
<div class="well bs-component">
<%= form_for(@project, :html => {:class => "form-horizontal"}) do |f| %>
  <fieldset>
  <legend><%= @legend %></legend>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :name, class: "col-lg-2 control-label" %><br>
    <div class="col-lg-10">
    <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "col-lg-2 control-label" %><br>
        <div class="col-lg-10">

    <%= f.radio_button :active, true, :checked => (@project.active), :value => true %> Active</br>
    <%= f.radio_button :active, false, :checked => (!@project.active), :value => true %> Inactive</br>
    </div>
  </div>

  <!-- add collaborators -->

  <% if !@project.collaborators.empty? %>
    <div class="form-group">
      <%= f.label :collaborators, class: "col-lg-2 control-label" %>
      <% @project.collaborators.each do |collaborator| %>
        <%= link_to collaborator.user.name, collaborator.user, class: "col-lg-2 control-label" %>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :add_a_collaborator, class: "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.collection_select :user, User.not_a_collaborator(@project), :id, :name %>
    </div>
  </div>

  <div class="actions">
    <%= f.button "Submit", class: "btn btn-primary" %>
  </div>
  </fieldset>
<% end %>
</div>
</div>
</div>

app/views/projects/edit.html.erb
<% @legend = "Edit This Project" %>

<%= render 'form' %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.admin.user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<% @legend = "New Project" %>

<%= render 'form' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div id="project-title">

  <h2><a href="<%= @project.url %>"><%= @project.name %></a>
    <% if logged_in? && current_user.admin.id == @project.admin_id %>
      <a href="<%= edit_project_path(@project) %>" class="btn btn-primary btn-sm">Edit Project</a>
    <% else %>
      <p>
        <strong>Admin:</strong>
        <%= link_to @project.admin.user.name, @project.admin.user %>
      </p>
    <% end %>
  </h2>

  <% if !@project.description == nil %>
    <p>
      <strong>Description:</strong>
      <%= @project.description %>
    </p>
  <% end %>
</div>

<div class="row">
  <div id="top-header">
    <div id="collaborators">
      <div class="list-group">
        <div class="col-xs-4">
          <div class="list-group-item active">
            Collaborators
          </div>
            <% @project.collaborators.each do |collaborator| %>
              <%= link_to collaborator.user.name, collaborator.user, class: "list-group-item" %>
            <% end %>
          </div>

          <div class="col-xs-4">
            <div id="languages">
            </div>
          </div>

          <div class="col-xs-4">
            <div class="list-group-item active">
              Five Most Recent Commits
            </div>
              <% @project.five_most_recent_commits.each do |commit| %>
              <%= link_to project_commit_path(@project, commit), class: "list-group-item" do %>
              <%= commit.message %>:
              <br />
              <%= commit.date.httpdate %>
              <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<br><br><br>

<div class="row">
  <!-- Milestones -->
  <div class="col-xs-4">
    <div id="milestones">


        <div class="list-group">
        <%= link_to "Five Most Recent Milestones", project_milestones_path(@project), class: "list-group-item active" %>
        <% @project.five_most_recent_milestones.each do |milestone| %>
              <%= link_to project_milestone_path(@project, milestone), class: "list-group-item" do %>
              <%= milestone.title %>:
              <br />
              <%= milestone.description %>
              <% end %>
        <% end %>
      </div>

      <% if logged_in? && current_user.id == @project.admin_id %>
        <p><%= link_to "New Milestone", new_project_milestone_path(@project), class: "btn btn-primary btn-sm" %></p>
      <% end %>
    </div>
  </div>

  <!-- Issues -->
  <div class="col-xs-4">
    <div id="issues">

      <div class="list-group">
        <%= link_to "Five Most Recent Issues", project_issues_path(@project), class: "list-group-item active"%>
        <% @project.five_most_recent_issues.each do |issue| %>
              <%= link_to project_issue_path(@project, issue), class: "list-group-item" do %>
              <%= issue.title %>
              <br />
              <%= issue.body %>
              <% end %>
        <% end %>
      </div>
      <% if logged_in? && current_user.id == @project.admin_id %>
        <p><%= link_to "New Issue", new_project_issue_path(@project), class: "btn btn-primary btn-sm" %></p>
      <% end %>
    </div>
  </div>

  <!-- Feed -->
  <div class="col-xs-4">
    <% if logged_in? %>
      <div id="feed">
      </div>
    <% end %>
  </div>
</div>