config/routes.rb
Rails.application.routes.draw do

  resources :commits
  root 'dashboard#root'
  get '/projects/dashboard' => 'projects#dashboard'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  get '/projects/:id/get_recent_activity' => 'projects#get_recent_activity'
  get '/projects/:id/get_language_statistics' => 'projects#get_language_statistics'

  resources :projects do
    resources :milestones
    resources :issues
    resources :commits
  end
  resources :users

  get '/login' => 'sessions#new'
  get '/auth/github/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/analytics' => 'analytics#index'
  get '/analytics/1' => 'analytics#projects_vs_collaborators'#, :defaults => { :format => 'json' }
  get '/analytics/2' => 'analytics#number_of_commits_for_active_projects'

  post '/event_handler' => 'dashboard#event_handler'
  get '/notifications' => 'dashboard#notifications'

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/" data-no-turbolink='true'>Gitr</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <li><%= link_to "User Directory", users_path %></li>
        <li><%= link_to "Project Directory", projects_path %></li>
        <li><%= link_to "Analytics Page", analytics_path %></li>
       <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <li><%= link_to "Logged in as #{current_user.name}", user_path(current_user) %></li>
      <li><%= link_to "Create a project", new_project_path %></li>
      <li><%= link_to 'Log out', logout_path %></li>
      <% else %>
      	<li><%= link_to 'Log in with Github', login_path %></li>
      <% end %>
        <!--<li><a href="#">Link</a></li>-->
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//d3js.org/d3.v3.min.js" charset="utf-8" type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "layouts/navbar" %>
<% if request.env["PATH_INFO"] != '/' %>
  <div class="container">
<% end %>
    <%= yield %>
<% if request.env["PATH_INFO"] != '/' %>
  </div>
<% end %>

</body>
</html>